apiVersion: v1
kind: Service
metadata:
  name: landslide-service
spec:
  type: LoadBalancer   # 🔥 change this
  selector:
    app: landslide-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000